apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: aline
  labels:
    aline.component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aline.component: gateway
    spec:
      containers:
      - name: gateway
        image: lyndasm/aline-gateway
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_SERVICE_HOST
          value: server-cluster-ip
        - name: PORTAL_LANDING
          value: landing-service
        - name: PORTAL_DASHBOARD
          value: member-service
        - name: PORTAL_ADMIN
          value: admin-service
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
