apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: account
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: account
  template:
    metadata:
      labels:
        aline.service: account
    spec:
      containers:
      - name: account
        image: lyndasm/aline-account-microservice
        ports:
          - containerPort: 8072
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: account
  name: account
spec:
  ports:
    - name: account-port
      port: 8072
      targetPort: 8072
  selector:
    aline.service: account
