apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: admin
  template:
    metadata:
      labels:
        aline.service: admin
    spec:
      containers:
      - name: admin
        image: lyndasm/aline-admin
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: admin
  name: admin
spec:
  ports:
    - name: admin-port
      port: 3000
      targetPort: 80
  selector:
    aline.service: admin
