apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-12-29T07:17:07Z"
  generation: 1
  labels:
    app: aline-gateway
  name: aline-gateway
  namespace: default
  resourceVersion: "99340"
  uid: bb2ee486-5ccd-4244-9466-52df327daa3d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aline-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aline-gateway
    spec:
      containers:
      - image: lyndasm/aline-gateway
        imagePullPolicy: Always
        name: aline-gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-12-29T07:17:10Z"
    lastUpdateTime: "2022-12-29T07:17:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-12-29T07:17:07Z"
    lastUpdateTime: "2022-12-29T07:17:10Z"
    message: ReplicaSet "aline-gateway-594975b944" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
