apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-12-29T07:16:56Z"
  generation: 1
  labels:
    app: aline-mysql
  name: aline-mysql
  namespace: default
  resourceVersion: "99282"
  uid: 834590dd-f911-4048-aa0b-fef21a32ac08
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aline-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aline-mysql
    spec:
      containers:
      - image: lyndasm/aline-mysql
        imagePullPolicy: Always
        name: aline-mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-12-29T07:16:58Z"
    lastUpdateTime: "2022-12-29T07:16:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-12-29T07:16:56Z"
    lastUpdateTime: "2022-12-29T07:16:58Z"
    message: ReplicaSet "aline-mysql-6c9466cc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
