apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: bank
  name: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: bank
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aline.service: bank
    spec:
      containers:
      - name: bank
        image: lyndasm/aline-bank-microservice
        ports:
          - containerPort: 8083
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
