apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: card
  name: card
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: card
  template:
    metadata:
      labels:
        aline.service: card
    spec:
      containers:
      - name: card
        image: lyndasm/aline-card-microservice
        ports:
          - containerPort: 8084
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: card
  name: card
spec:
  ports:
    - name: card-port
      port: 8084
      targetPort: 8084
  selector:
    aline.service: card