apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: aline
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 3000
    port: 80
  selector:
    aline.component: client
    task: admin
---
apiVersion: v1
kind: Service
metadata:
  name: landing-service
  namespace: aline
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 4200
    port: 80
  selector:
    aline.component: client
    task: landing
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: aline
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 3007
    port: 80
  selector:
    aline.component: client
    task: member