apiVersion: v1
kind: Service
metadata:
  name: landing-service
  namespace: aline
  labels:
    aline.component: landing
spec:
  type: LoadBalancer
  selector:
    aline.component: landing
  ports:
    - protocol: TCP
      name: landing
      port: 4200
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: aline
  labels:
    aline.component: member
spec:
  type: LoadBalancer
  selector:
    aline.component: member
  ports:
    - protocol: TCP
      name: member
      port: 3007
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: aline
  labels:
    aline.component: admin
spec:
  type: LoadBalancer
  selector:
    aline.component: admin
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 80