apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aline-dbdata
  annotations:
    cluster-name: aline-financial
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
