apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    aline.component: gateway
spec:
  ports:
    - name: gateway
      port: 8080
      targetPort: 8080
  selector:
    aline.component: gateway