# 1. Import the nginx ingress controller
# `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/cloud/deploy.yaml`

# 2. Apply yaml files
# `kubectl apply -f .`

# 3. Modify /etc/hosts to add `alinefinancial.com` to localhost.

# 4. pages should be accessible at 
# `alinefinancial.com/landing` and `alinefinancial.com/member`

# 5. Remove pods when done
# `kubectl delete -f .`
---
apiVersion: v1
kind: Namespace
metadata:
  name: aline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
  namespace: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: client
      app: landing
  template:
    metadata:
      labels:
        aline.component: client
        app: landing
    spec:
      containers:
      - name: landing
        image: lyndasm/aline-landing
        ports:
          - containerPort: 4200
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  namespace: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: client
      app: member
  template:
    metadata:
      labels:
        aline.component: client
        app: member
    spec:
      containers:
      - name: member
        image: lyndasm/aline-member
        ports:
          - containerPort: 3007
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: landing-service
  namespace: aline
spec:
  type: LoadBalancer
  selector:
    aline.component: client
    app: landing
  ports:
    - protocol: TCP
      name: landing
      port: 80
      targetPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: aline
spec:
  type: LoadBalancer
  selector:
    aline.component: client
    app: member
  ports:
    - protocol: TCP
      name: member
      port: 80
      targetPort: 3007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: aline
spec:
  rules:
    - host: alinefinancial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-service
                port:
                  number: 80
          - path: /landing
            pathType: Prefix
            backend:
              service:
                name: landing-service
                port:
                  number: 80
          - path: /member
            pathType: Prefix
            backend:
              service:
                name: member-service
                port:
                  number: 80