apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: aline
  labels:
    aline.component: mysql
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: aline
  labels:
    aline.component: mysql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: aline
  labels:
    aline.component: mysql
spec:
  selector:
    matchLabels:
      aline.component: mysql
  template:
    metadata:
      labels:
        aline.component: mysql
    spec:
      containers:
        - name: mysql
          image: lyndasm/aline-mysql:kubernetes
          env:
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: DB_PASSWORD
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: alinedb
            - name: APP_SERVICE_HOST
              value: server-cluster-ip
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: alinedb-persistance-storage
      volumes:
        - name: alinedb-persistance-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip
  namespace: aline
  labels:
    aline.component: mysql
spec:
  selector:
    aline.component: mysql
  ports:
    - port: 3306
      targetPort: 3306
