version: "3.8"

x-variables: &variables
  DB_USERNAME: user
  DB_PASSWORD: really_good_password
  DB_HOST: mysql
  DB_PORT: 3306
  DB_NAME: alinedb
  APP_SERVICE_HOST: host.docker.internal
  ENCRYPT_SECRET_KEY: "001104a5cbe95ed3bff1495a1ae92a28"
  JWT_SECRET_KEY: "my-32-character-ultra-secure-and-ultra-long-secret"

x-react-variables: &react-variables
  REACT_APP_API: http://gateway:8080/api

services:
  # Database
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: really_good_password
      MYSQL_PASSWORD: really_good_password
      MYSQL_USER: user
      MYSQL_DATABASE: alinedb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  # Node Projects
  admin:
    build:
      context: ./aline-admin-portal
      dockerfile: ../Dockerfile.node
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    environment:
      <<: *react-variables
      PORT: ${ADMIN_PORT}

  dashboard:
    build:
      context: ./member-dashboard
      dockerfile: ../Dockerfile.node
    ports:
      - ${DASHBOARD_PORT}:${DASHBOARD_PORT}
    environment:
      - PORT=${DASHBOARD_PORT}

  landing:
    build:
      context: ./aline-landing-portal
      dockerfile: ../Dockerfile.node
    ports:
      - ${LANDING_PORT}:${LANDING_PORT}
    environment:
      <<: *react-variables
      PORT: ${LANDING_PORT}

  # Maven projects
  gateway:
    build:
      context: ./aline-gateway
      dockerfile: ../Dockerfile.maven
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      <<: *variables
      APP_DIR: .
      APP_PORT: ${GATEWAY_PORT}
      TARGET: ./target

  account:
    build:
      context: ./aline-account-microservice
      dockerfile: ../Dockerfile.maven
    depends_on:
      - mysql
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    environment:
      <<: *variables
      APP_DIR: ./account-microservice
      APP_PORT: ${ACCOUNT_PORT}
      TARGET: ./aline-account-microservice/account-microservice/target

  bank:
    build:
      context: ./aline-bank-microservice
      dockerfile: ../Dockerfile.maven
    depends_on:
      - mysql
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    environment:
      <<: *variables
      APP_DIR: ./bank-microservice
      APP_PORT: ${BANK_PORT}
      TARGET: /aline-bank-microservice/bank-microservice/target

  card:
    build:
      context: ./aline-card-microservice
      dockerfile: ../Dockerfile.maven
    depends_on:
      - mysql
    ports:
      - ${CARD_PORT}:${CARD_PORT}
    environment:
      <<: *variables
      APP_DIR: ./card-microservice
      APP_PORT: ${CARD_PORT}
      TARGET: /aline-card-microservice/card-microservice/target

  transaction:
    build:
      context: ./aline-transaction-microservice
      dockerfile: ../Dockerfile.maven
    depends_on:
      - mysql
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    environment:
      <<: *variables
      APP_DIR: ./transaction-microservice
      APP_PORT: ${TRANSACTION_PORT}
      TARGET: /aline-transaction-microservice/transaction-microservice/target

  underwriter:
    build:
      context: ./aline-underwriter-microservice
      dockerfile: ../Dockerfile.maven
    depends_on:
      - mysql
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    environment:
      <<: *variables
      APP_DIR: ./underwriter-microservice
      APP_PORT: ${UNDERWRITER_PORT}
      TARGET: /aline-underwriter-microservice/underwriter-microservice/target

  user:
    build:
      context: ./aline-user-microservice
      dockerfile: ../Dockerfile.maven
    depends_on:
      - mysql
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      <<: *variables
      APP_DIR: ./user-microservice
      APP_PORT: ${USER_PORT}
      TARGET: /aline-user-microservice/user-microservice/target


volumes:
  db-data: