version: "3.8"

x-variables: &variables
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}

x-react-variables: &react-variables
  REACT_APP_MEMBER_DASHBOARD_URL: ${REACT_APP_MEMBER_DASHBOARD_URL}
  REACT_APP_API_BASEURL: ${REACT_APP_API_BASEURL}
  REACT_APP_API: ${REACT_APP_API}

volumes:
  db-data:

services:
  mysql:
    image: lyndasm/aline-mysql:kubernetes
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  # Frontend Projects
  member:
    build:
      context: ./aline-member-dashboard
      dockerfile: ../Dockerfile.node
    ports:
      - ${MEMBER_PORT}:80
    environment:
      <<: *react-variables
      PORTAL_LANDING: ${PORTAL_LANDING}
      PORTAL_DASHBOARD: ${PORTAL_DASHBOARD}
      PORTAL_ADMIN: ${PORTAL_ADMIN}

  admin:
    build:
      context: ./aline-admin-portal
      dockerfile: ../Dockerfile.node
    ports:
      - ${ADMIN_PORT}:80
    environment:
      <<: *react-variables

  landing:
    build:
      context: ./aline-landing-portal
      dockerfile: ../Dockerfile.node
    ports:
      - ${LANDING_PORT}:80
    environment:
      <<: *react-variables

  # Maven Projects
  gateway:
    image: lyndasm/aline-gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      <<: *variables
      APP_SERVICE_HOST: ${APP_SERVICE_HOST}

  account:
    build:
      context: ./aline-account-microservice
      dockerfile: ../Dockerfile.maven
      args:
        - APP_DIR=./account-microservice/target
    depends_on:
      - mysql
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    environment:
      <<: *variables
      APP_PORT: ${ACCOUNT_PORT}

  bank:
    build:
      context: ./aline-bank-microservice
      dockerfile: ../Dockerfile.maven
      args:
        - APP_DIR=./bank-microservice/target
    depends_on:
      - mysql
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    environment:
      <<: *variables
      APP_PORT: ${BANK_PORT}

  card:
    build:
      context: ./aline-card-microservice
      dockerfile: ../Dockerfile.maven
      args:
        - APP_DIR=./card-microservice/target
    depends_on:
      - mysql
    ports:
      - ${CARD_PORT}:${CARD_PORT}
    environment:
      <<: *variables
      APP_PORT: ${CARD_PORT}

  transaction:
    build:
      context: ./aline-transaction-microservice
      dockerfile: ../Dockerfile.maven
      args:
        - APP_DIR=./transaction-microservice/target
    depends_on:
      - mysql
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    environment:
      <<: *variables
      APP_PORT: ${TRANSACTION_PORT}

  underwriter:
    build:
      context: ./aline-underwriter-microservice
      dockerfile: ../Dockerfile.maven
      args:
        - APP_DIR=./underwriter-microservice/target
    depends_on:
      - mysql
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    environment:
      <<: *variables
      APP_PORT: ${UNDERWRITER_PORT}

  user:
    build:
      context: ./aline-user-microservice
      dockerfile: ../Dockerfile.maven
      args:
        - APP_DIR=./user-microservice/target
    depends_on:
      - mysql
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      <<: *variables
      APP_PORT: ${USER_PORT}
