version: "3.8"

services:
  mysql:
    image: lyndasm/aline-mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  member:
    image: lyndasm/aline-member
    ports:
      - 3007:80

  admin:
    image: lyndasm/aline-admin
    ports:
      - 3000:80

  landing:
    image: lyndasm/aline-landing
    ports:
      - 4200:80

  gateway:
    image: lyndasm/aline-gateway
    ports:
      - 8080:8080

  account:
    image: lyndasm/aline-account-microservice
    depends_on:
      - mysql
    ports:
      - 8072:8072

  bank:
    image: lyndasm/aline-bank-microservice
    depends_on:
      - mysql
    ports:
      - 8083:8083

  card:
    image: lyndasm/aline-card-microservice
    depends_on:
      - mysql
    ports:
      - 8084:8084

  transaction:
    image: lyndasm/aline-transaction-microservice
    depends_on:
      - mysql
    ports:
      - 8073:8073

  underwriter:
    image: lyndasm/aline-underwriter-microservice
    depends_on:
      - mysql
    ports:
      - 8071:8071

  user:
    image: lyndasm/aline-user-microservice
    depends_on:
      - mysql
    ports:
      - 8070:8070

volumes:
  db-data:
