version: "3.8"

x-variables: &variables
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  APP_SERVICE_HOST: ${APP_SERVICE_HOST}

x-react-variables: &react-variables
  REACT_APP_API_BASEURL: http://localhost:${GATEWAY_PORT}
  REACT_APP_API: http://localhost:${GATEWAY_PORT}/api

services:
  # Database
  mysql:
    image: lyndasm/aline-mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  # Frontend Projects
  member:
    image: lyndasm/aline-member
    ports:
      - ${MEMBER_PORT}:80
    environment:
      <<: *react-variables

  admin:
    image: lyndasm/aline-admin
    ports:
      - ${ADMIN_PORT}:80
    environment:
      <<: *react-variables

  landing:
    image: lyndasm/aline-landing
    ports:
      - ${LANDING_PORT}:80
    environment:
      <<: *react-variables

  # Maven Projects
  gateway:
    image: lyndasm/aline-gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      <<: *variables
      APP_PORT: ${GATEWAY_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  account:
    image: lyndasm/aline-account-microservice
    depends_on:
      - mysql
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    environment:
      <<: *variables
      APP_PORT: ${ACCOUNT_PORT}

  bank:
    image: lyndasm/aline-bank-microservice
    depends_on:
      - mysql
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    environment:
      <<: *variables
      APP_PORT: ${BANK_PORT}

  card:
    image: lyndasm/aline-card-microservice
    depends_on:
      - mysql
    ports:
      - ${CARD_PORT}:${CARD_PORT}
    environment:
      <<: *variables
      APP_PORT: ${CARD_PORT}

  transaction:
    image: lyndasm/aline-transaction-microservice
    depends_on:
      - mysql
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    environment:
      <<: *variables
      APP_PORT: ${TRANSACTION_PORT}

  underwriter:
    image: lyndasm/aline-underwriter-microservice
    depends_on:
      - mysql
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    environment:
      <<: *variables
      APP_PORT: ${UNDERWRITER_PORT}

  user:
    image: lyndasm/aline-user-microservice
    depends_on:
      - mysql
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      <<: *variables
      APP_PORT: ${USER_PORT}

volumes:
  db-data:
