apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip
  namespace: aline
  labels:
    aline.component: server
spec:
  type: ClusterIP
  selector:
    aline.component: server
  ports:
  - name: user-port
    protocol: TCP
    port: 8070
    targetPort: 8070
  - name: bank-port
    protocol: TCP
    port: 8083
    targetPort: 8083