version: "3.8"

services:
  ecsworker-in-region:
    environment: 
        - SQS_QUEUE_URL=https://sqs.us-west-1.amazonaws.com/052911266688/main-queue
        - EFS_SOURCE_FOLDER=/data/sourcefolder/             
        - EFS_DESTINATION_FOLDER=/data/destinationfolder/              
        - AWS_REGION=us-west-1
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/ecsworker:amd64-slim 
    volumes:
        - efs-share:/data
    x-aws-role:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sqs:*
          Resource: arn:aws:sqs:us-west-1:052911266688:main-queue
volumes:
  efs-share:

x-variables: &variables
  DB_USERNAME: admin
  DB_PASSWORD: really_good_password
  DB_HOST: alinedb.ckgn8hh1chiz.us-west-1.rds.amazonaws.com
  DB_PORT: 3306
  DB_NAME: lf_alinedb
  APP_SERVICE_HOST: localhost

x-react-variables: &react-variables
  REACT_APP_MEMBER_DASHBOARD_URL: member.alinefinanncial.com
  REACT_APP_API_BASEURL: api.alinefinancial.com/api/
  REACT_APP_API: api.alinefinancial.com

services:
  # # Frontend Projects
  # member:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-member-dashboard
  #   ports:
  #     - 3007:80
  #   environment:
  #     <<: *react-variables

  # admin:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-admin-portal
  #   ports:
  #     - 3000:80
  #   environment:
  #     <<: *react-variables

  landing:
    platform: linux/amd64
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-landing-portal
    ports:
      - 4200:80
    environment:
      <<: *react-variables
      
  # # Maven Projects
  # gateway:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-gateway
  #   ports:
  #     - 8080:8080
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8080
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 20s

  # account:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-account-microservice
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 8072:8072
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8072

  # bank:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-bank-microservice
  #   depends_on:
  #     - mysql
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8083

  # card:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-card-microservice
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 8084:8084
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8084

  # transaction:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-transaction-microservice
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 8073:8073
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8073

  # underwriter:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-underwriter-microservice
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 8070:8070
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8070

  # user:
  #   platform: linux/amd64
  #   x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-1:052911266688:secret:DockerHubAccessToken"
  #   image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-user-microservice
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 8071:8071
  #   environment:
  #     <<: *variables
  #     APP_PORT: 8071

