apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
  namespace: aline
  labels:
    aline.component: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: landing
  template:
    metadata:
      labels:
        aline.component: landing
    spec:
      containers:
      - name: landing
        image: lyndasm/aline-landing:kubernetes
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
      restartPolicy: Always
