apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: aline
  labels:
    aline.component: member
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    aline.component: member
  ports:
    - protocol: TCP
      name: member
      port: 3007
      targetPort: 80