apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    aline.component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        aline.component: mysql
    spec:
      containers:
      - name: mysql
        image: lyndasm/aline-mysql:kubernetes
        ports:
          - containerPort: 3306
            name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: DB_PASSWORD
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
            subPath: mysql
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

