def app
pipeline {
    agent any
    environment {
        GIT_COMMIT_HASH = getCommitSha()
        registry = "lyndasm/demo-app"
        registryCredential = 'docker-login'
    }
    stages {
        stage('init') {
            steps {
                script {
                    app = load "script.groovy"
                }
            }
        }
        stage('setup') {
            steps {
                script {
                    app.setup()
                }
            }
        }
        stage('build') {
            steps {
                script {
                    app.build()
                }
            }
        }
        stage('build image') {
            steps {
                script {
                    app.buildImage()
                }
            }
        }
        stage('push image') {
            steps {
                script {
                    app.pushImage()
                }
            }
        }
        
    }
}