def gv
pipeline {
    agent any
    environment {
        GIT_COMMIT_HASH = getCommitSha()
        registry = "lyndasm/demo-app"
        registryCredential = 'docker-login'
    }
    stages {
        stage('init') {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage('setup') {
            steps {
                script {
                    gv.setup()
                }
            }
        }
        stage('build') {
            steps {
                script {
                    gv.build()
                }
            }
        }
        stage('build image') {
            steps {
                script {
                    gv.buildImage()
                }
            }
        }
        stage('push image') {
            steps {
                script {
                    gv.pushImage()
                }
            }
        }
        
    }
}