apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: aline
  labels:
    aline.component: gateway
spec:
  type: LoadBalancer
  ports:
    - name: gateway
      port: 80
  selector:
    aline.component: gateway