version: "3.9"

x-variables: &variables
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  APP_SERVICE_HOST: ${APP_SERVICE_HOST}

volumes:
  db-data:

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "user" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  bank:
    image: ${REGISTRY}/lf-aline-bank-microservice:latest
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    depends_on:
      mysql:
        condition: service_started
    environment:
      <<: *variables
      APP_PORT: ${BANK_PORT}
    restart: on-failure


