version: "3"

volumes:
  jenkins_home:
  # sonarqube_data:
  # sonarqube_extensions:
  # sonarqube_logs:
  # postgresql:
  # postgresql_data:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/git_host
    environment:
    # allows checkout from local repositories
      JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    ports:
      - 8080:8080
      - 50000:50000
    # networks:
    #   - minikube

  # sonarqube:
  #   image: sonarqube
  #   depends_on:
  #     - postgres
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #     SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #   ports:
  #     - 9000:9000

  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #     POSTGRES_DB: sonar
  #   volumes:
  #     - postgresql:/var/lib/postgresql
  #     - postgresql_data:/var/lib/postgresql/data

# networks:
#   minikube:
#     name: minikube
#     external: true
