apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: aline-underwriter-microservice
  name: aline-underwriter-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: aline-underwriter-microservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: aline-underwriter-microservice
    spec:
      containers:
        - image: lyndasm/aline-underwriter-microservice
          name: aline-underwriter-microservice
          ports:
            - containerPort: 8071
          resources: {}
      restartPolicy: Always
status: {}
