apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: aline-transaction-microservice
  name: aline-transaction-microservice
spec:
  ports:
    - name: "8073"
      port: 8073
      targetPort: 8073
  selector:
    io.kompose.service: aline-transaction-microservice
status:
  loadBalancer: {}
